Traceback (most recent call last):
  File "/home/bleyerj/miniconda3/envs/fenicsx-v0.9/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/bleyerj/miniconda3/envs/fenicsx-v0.9/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bleyerj/miniconda3/envs/fenicsx-v0.9/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bleyerj/miniconda3/envs/fenicsx-v0.9/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/bleyerj/miniconda3/envs/fenicsx-v0.9/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/bleyerj/miniconda3/envs/fenicsx-v0.9/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/bleyerj/miniconda3/envs/fenicsx-v0.9/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
dx = ufl.Measure("dx", domain=domain, subdomain_data=cells)
ds = ufl.Measure("ds", domain=domain, subdomain_data=facets)
dx_int = ufl.Measure("dx", domain=interface_mesh)
dInt = ufl.Measure(
    "dS",
    domain=domain,
    subdomain_data=[(INT_TAG, interface_entities)],
    subdomain_id=INT_TAG,
)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[8], line 7[0m
[1;32m      2[0m ds [38;5;241m=[39m ufl[38;5;241m.[39mMeasure([38;5;124m"[39m[38;5;124mds[39m[38;5;124m"[39m, domain[38;5;241m=[39mdomain, subdomain_data[38;5;241m=[39mfacets)
[1;32m      3[0m dx_int [38;5;241m=[39m ufl[38;5;241m.[39mMeasure([38;5;124m"[39m[38;5;124mdx[39m[38;5;124m"[39m, domain[38;5;241m=[39minterface_mesh)
[1;32m      4[0m dInt [38;5;241m=[39m ufl[38;5;241m.[39mMeasure(
[1;32m      5[0m     [38;5;124m"[39m[38;5;124mdS[39m[38;5;124m"[39m,
[1;32m      6[0m     domain[38;5;241m=[39mdomain,
[0;32m----> 7[0m     subdomain_data[38;5;241m=[39m[(INT_TAG, [43minterface_entities[49m)],
[1;32m      8[0m     subdomain_id[38;5;241m=[39mINT_TAG,
[1;32m      9[0m )

[0;31mNameError[0m: name 'interface_entities' is not defined

