Traceback (most recent call last):
  File "/home/bleyerj/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/bleyerj/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
values = np.linspace(0, 1.0, 6)
x = V.tabulate_dof_coordinates()[:, 0]
plt.figure()
plt.gca().set_prop_cycle(color=plt.cm.turbo(values))
for value in values:
    d_imp.value = value
    fem.set_bc(d.vector, bcs)

    tao.solve(d.vector)
    dvals = d.vector.array

    h = plt.plot(x, dvals, "o")
    l0 = ell0.value
    ppos = lambda x: np.maximum(x, np.zeros_like(x))
    d_an = (ppos(np.sqrt(value) - np.abs(x / 2 / l0))) ** 2
    plt.plot(x, d_an, "-", color=h[0].get_color())
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mError[0m                                     Traceback (most recent call last)
Cell [0;32mIn[7], line 9[0m
[1;32m      6[0m d_imp[38;5;241m.[39mvalue [38;5;241m=[39m value
[1;32m      7[0m fem[38;5;241m.[39mset_bc(d[38;5;241m.[39mvector, bcs)
[0;32m----> 9[0m [43mtao[49m[38;5;241;43m.[39;49m[43msolve[49m[43m([49m[43md[49m[38;5;241;43m.[39;49m[43mvector[49m[43m)[49m
[1;32m     10[0m dvals [38;5;241m=[39m d[38;5;241m.[39mvector[38;5;241m.[39marray
[1;32m     12[0m h [38;5;241m=[39m plt[38;5;241m.[39mplot(x, dvals, [38;5;124m"[39m[38;5;124mo[39m[38;5;124m"[39m)

File [0;32mPETSc/TAO.pyx:468[0m, in [0;36mpetsc4py.PETSc.TAO.solve[0;34m()[0m

[0;31mError[0m: error code 56
[0] TaoSolve() line 220 in ./src/tao/interface/taosolver.c
[0] TaoSetUp() line 274 in ./src/tao/interface/taosolver.c
[0] TaoSetUp_BNTR() line 209 in ./src/tao/bound/impls/bnk/bntr.c
[0] No support for this operation for this object type
[0] Must use a trust-region CG method for KSP (KSPNASH, KSPSTCG, KSPGLTR)

