Traceback (most recent call last):
  File "/home/bleyerj/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/bleyerj/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
degree = 2
V = fem.functionspace(domain, ("P", degree, dim))

u_sol = fem.Function(V, name="Displacement")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m degree [38;5;241m=[39m [38;5;241m2[39m
[0;32m----> 2[0m V [38;5;241m=[39m [43mfem[49m[38;5;241;43m.[39;49m[43mfunctionspace[49m[43m([49m[43mdomain[49m[43m,[49m[43m [49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mP[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mdegree[49m[43m,[49m[43m [49m[43mdim[49m[43m)[49m[43m)[49m
[1;32m      4[0m u_sol [38;5;241m=[39m fem[38;5;241m.[39mFunction(V, name[38;5;241m=[39m[38;5;124m"[39m[38;5;124mDisplacement[39m[38;5;124m"[39m)

File [0;32m/usr/lib/petsc/lib/python3/dist-packages/dolfinx/fem/function.py:527[0m, in [0;36mfunctionspace[0;34m(mesh, element, form_compiler_options, jit_options)[0m
[1;32m    524[0m     ufl_e [38;5;241m=[39m element  [38;5;66;03m# type: ignore[39;00m
[1;32m    526[0m [38;5;66;03m# Check that element and mesh cell types match[39;00m
[0;32m--> 527[0m [38;5;28;01mif[39;00m [43mufl_e[49m[38;5;241;43m.[39;49m[43mcell[49m() [38;5;241m!=[39m mesh[38;5;241m.[39mufl_domain()[38;5;241m.[39mufl_cell():
[1;32m    528[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mNon-matching UFL cell and mesh cell shapes.[39m[38;5;124m"[39m)
[1;32m    530[0m [38;5;66;03m# Compile dofmap and element and create DOLFIN objects[39;00m

[0;31mAttributeError[0m: 'tuple' object has no attribute 'cell'

